BackEnd/receitas/urls.py
from django.contrib import admin
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^home/', include('site_receitas.urls', namespace='site_receitas')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

BackEnd/site_receitas/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.Home.as_view(), name='home'),
    url(r'^cadastroUsuarioJson/', views.CadastroUsuario.as_view()),
    url(r'^cadastroUsuario/', views.cadastroUsuarioRender, name="Cadastrar Usuario"),
    url(r'^cadastroReceitaJson/', views.CadastroReceita.as_view(), name="Cadastrar Receita"),
    url(r'^cadastroReceita/', views.cadastroRender, name="TelaCadastrarReceita"),
    url(r'^doces/', views.ExibirReceitasDoces.as_view(), name="Doces"),
    url(r'^salgados/', views.ExibirReceitasSalgados.as_view(), name="Salgados"),
    url(r'^bebidas/', views.ExibirReceitasBebidas.as_view(), name="Bebidas"),
    url(r'^(?P<id>\d+)/$', views.detalheReceita, name="detalheReceita"),
    url(r'^(?P<tipo>xml|simples)/(?P<id>\d+)/$', views.detalheReceita, name="simples_xml"),
    url(r'^entrar/$', views.entrar, name='entrar'),
    url(r'^sair/$', views.sair, name='sair'),
    url(r'^cadastroComentario/', views.CadastroComentario.as_view(), name="Cadastrar Comentario"),
    url(r'^avaliar/', views.Avaliar.as_view(), name="Avaliar"),
]

BackEnd/site_receitas/models.py
from django.db import models
from django.contrib.auth.base_user import AbstractBaseUser
from django.contrib.auth.models import PermissionsMixin
from .managers import UserManager

class Usuario(AbstractBaseUser, PermissionsMixin):
    nome = models.CharField(max_length=100)
    nascimento = models.DateField(null=True, blank=True)
    cidade = models.CharField(max_length=150, null=True, blank=True)
    estado = models.CharField(max_length=2, null=True, blank=True)
    telefone = models.CharField(max_length=14, null=True ,blank=True)
    usuario = models.EmailField(max_length=50, unique=True)

    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)

    objects = UserManager()

    USERNAME_FIELD = 'usuario'
    REQUIRED_FIELDS = ['nome']

    def get_full_name(self):
        return self.nome

    def get_short_name(self):
        return self.nome

class Receita(models.Model):

    DOCES = "d"
    SALGADOS = "s"
    BEBIDAS = "b"

    ESCOLHA_CATEGORIA = (
        (DOCES, 'Doce'),
        (SALGADOS, 'Salgado'),
        (BEBIDAS, 'Bebidas'),
    )

    dataCadastro = models.DateField(auto_now_add=True, null=True)
    autor = models.CharField(max_length=100, null=True)
    nome_receita = models.CharField(max_length=50, verbose_name="nome da receita", null=True)
    descricao = models.TextField(max_length=300, verbose_name="descrição", null=True)
    #imagems, relação uma para muitos então criou-se a classe imagem e a relação se da pela chave estrangeira fk_receita
    categoria = models.CharField(max_length=1, choices=ESCOLHA_CATEGORIA, default="SC")
    procoes = models.PositiveIntegerField(verbose_name="porções", default=0)
    val_nutricional = models.PositiveIntegerField(verbose_name="valor nutricional", default=0)
    #ingredientes, relação um para muitos, criou-se a classe ingrediente e a relação se da pela chave estrangeira fk_receita
    tempo_preparo = models.PositiveIntegerField(verbose_name="tempo de preparo", default=0)
    instrucoes_preparo = models.TextField(max_length=800, verbose_name="instruções de preparo", null=True)
    metodo_cozimento = models.CharField(max_length=100, verbose_name="método de cozimento", null=True)
    rating = models.PositiveIntegerField(default=0)
    num_votos = models.PositiveIntegerField(default=0)

    class Meta:
        ordering = ['dataCadastro', '-nome_receita', 'rating']

    def __str__(self):
        return self.nome_receita

    def __unicode__(self):
        return self.nome_receita

class Imagem(models.Model):
    fk_receita_imagem = models.ForeignKey('Receita', related_name='imagens', on_delete=models.CASCADE, default=1)
    imagem = models.ImageField(upload_to="static/images/")

    def __str__(self):
        return str(self.fk_receita_imagem)

    def __unicode__(self):
        return self.fk_receita_imagem

class Ingrediente(models.Model):
    fk_receita_ingrediente = models.ForeignKey('Receita', related_name='ingredientes', on_delete=models.CASCADE, default=0)
    nome_ingrediente = models.CharField(max_length=50, verbose_name="ingrediente")
    quantidade = models.PositiveIntegerField(default=0)
    unidade = models.CharField(max_length=50, default="su")

    def __str__(self):
        return ('%d %s: %s' % (self.quantidade, self.unidade, self.nome_ingrediente))

    def __unicode__(self):
        return ('%d %s: %s' % (self.quantidade, self.unidade, self.nome_ingrediente))

class Comentario(models.Model):
    fk_usuario_comentario = models.ForeignKey('Usuario', related_name="fk_usuario", on_delete=models.CASCADE, default=0)
    fk_receita_comentario = models.ForeignKey('Receita', related_name="comentarios", on_delete=models.CASCADE, default=0)
    texto_comentario = models.TextField(max_length=1000, verbose_name="Comentario")

    def __str__(self):
        return(self.fk_usuario_comentario.nome + " | " + self.fk_receita_comentario.nome_receita)

    def __unicode__(self):
        return(self.fk_usuario_comentario.nome)

    @property
    def nome_usuario(self):
        return self.fk_usuario_comentario.nome

BackEnd/site_receitas/forms.py
from django.forms import ModelForm
from .models import *

class UsuarioForm(ModelForm):
    class Meta:
        model = Usuario
        fields = ('nome', 'nascimento', 'cidade', 'estado', 'telefone', 'usuario')

class IngredienteForm(ModelForm):
    class Meta:
        model = Ingrediente
        fields = ('nome_ingrediente', 'quantidade', 'unidade' )

class ImagemForm(ModelForm):
    class Meta:
        model = Imagem
        fields = ('imagem',)

class ComentarioForm(ModelForm):
    class Meta:
        model = Comentario
        fields = '__all__'

BackEnd/site_receitas/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render
from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework import status
from rest_framework.renderers import TemplateHTMLRenderer
from django.http import Http404, HttpResponseRedirect
import json
from django.contrib.auth import authenticate, login, logout
from django.core.urlresolvers import reverse

from .models import *
from .serializers import *

# Create your views here.
class Home(APIView):

    renderer_classes = [TemplateHTMLRenderer,]
    template_name = 'index.html'

    def get(self, request, format=None):
        doces = Receita.objects.filter(categoria="d").order_by('-dataCadastro')[:3]
        serielizer_doces = ReceitaSerializer(doces, many=True)
        salgados = Receita.objects.filter(categoria="s").order_by('-dataCadastro')[:3]
        serielizer_salgados = ReceitaSerializer(salgados, many=True)
        bebidas = Receita.objects.filter(categoria="b").order_by('-dataCadastro')[:3]
        serielizer_bebidas = ReceitaSerializer(bebidas, many=True)

        context = {
            'doces': serielizer_doces.data,
            'salgados': serielizer_salgados.data,
            'bebidas': serielizer_bebidas.data
        }
        return Response(context)

def cadastroUsuarioRender(request):
    return render(request, 'cadastroUsuario.html')

class CadastroUsuario(APIView):

    # renderer_classes = [TemplateHTMLRenderer,]
    # template_name = 'cadastroUsuario.html'

    def get(self, request, format=None):
        return Response({})

    def post(self, request, format=None):
        print(request.data)
        serializer = UsuarioSerializer(data=request.data)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data, status=status.HTTP_201_CREATED)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

def cadastroRender(request):
    if request.user.is_authenticated:
        return render(request, 'cadastroReceita.html')
    else:
        context = {'errors': 'É necessário entrar para cadastrar uma receita'}
        return render(request, 'entrar.html', context)

class CadastroReceita(APIView):

    def get(self, request, format=None):
        return Response()

    def post(self, request, format=None):
        #print(json.loads(request.data['json_data']))
        serializer = ReceitaSerializer(data=json.loads(request.data['json_data']))
        #serializer = ReceitaSerializer(data=request.data)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data, status=status.HTTP_201_CREATED)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

class ExibirReceitasDoces(APIView):

    renderer_classes = [TemplateHTMLRenderer]
    template_name = 'doces.html'

    def get(self, request, format=None):
        doces = Receita.objects.filter(categoria="d").order_by('-dataCadastro')
        serielizer = ReceitaSerializer(doces, many=True)
        #print(serielizer.data)
        return Response({'doces': serielizer.data})

class ExibirReceitasSalgados(APIView):

    renderer_classes = [TemplateHTMLRenderer]
    template_name = 'salgados.html'

    def get(self, request, format=None):
        salgados = Receita.objects.filter(categoria="s").order_by('-dataCadastro')
        serializer = ReceitaSerializer(salgados, many=True)
        return Response({'salgados': serializer.data})

class ExibirReceitasBebidas(APIView):
    renderer_classes = [TemplateHTMLRenderer]
    template_name = 'bebidas.html'

    def get(self, request, format=None):
        bebidas = Receita.objects.filter(categoria="b").order_by('-dataCadastro')
        serializer = ReceitaSerializer(bebidas, many=True)
        return Response({'bebidas': serializer.data})

def detalheReceita(request, id, tipo = ''):
    try:
        receita = Receita.objects.get(id=id)
    except Receita.DoesNotExist:
        raise Http404
    serializer = ReceitaSerializer(receita)
    if tipo == 'xml':
        return render(request, 'receita.xml', {'receita': serializer.data}, content_type="application/xhtml+xml")
    elif tipo == 'simples':
        return render(request, 'simples.html', {'receita': serializer.data})
    else:
        return render(request, 'detalheReceita.html', {'receita': serializer.data})

def entrar(request):
    if request.method != 'POST':
        context = {'errors': ''}
        return render(request, 'entrar.html', context)
    else:
        username = request.POST['nome_usuario']
        password = request.POST['senha']
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return HttpResponseRedirect(reverse('site_receitas:home'))
        else:
            context = {'errors': 'E-mail ou senha incorretos.'}
            return render(request, 'entrar.html', context)

def sair(request):
    logout(request)
    return HttpResponseRedirect(reverse('site_receitas:home'))

class CadastroComentario(APIView):

    def post(self, request, format=None):
        serializer = ComentarioSerializer(data=request.data)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data, status=status.HTTP_201_CREATED)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

class Avaliar(APIView):

    def post(self, request, format=None):
        receita = Receita.objects.get(id = request.data['receita'])
        receita.rating = (receita.rating * receita.num_votos + int(request.data['nota'])) / (receita.num_votos + 1)
        receita.num_votos += 1
        receita.save()
        print("Deu certo!!!")
        return Response({}, status=status.HTTP_201_CREATED)

BackEnd/site_receitas/templates/base.html
<!--Augusto Torres dos Santos nºUSP 7144560
    Creunivar Toledo de Abreu nºUSP
    Guilherme José Acra nºUSP-->

<!DOCTYPE>
<html lang="pt-br">
  <head>
    <title>{% block title %} Ki Gostoso {% endblock %}</title>

    <meta charset="utf-8"/>
    <!--Let browser know website is optimized for mobile-->
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <!--Import Google Icon Font-->
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

    {% load static %}
    <!--Import materialize.css-->
    <link type="text/css" rel="stylesheet" href="{% static 'css/materialize.css' %}"  media="screen,projection"/>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/rateYo/2.3.2/jquery.rateyo.min.css">
  </head>

  <body class="card-panel yellow lighten-5">
    <div class="row">

      <!--header contendo o logo, login, cadastro e busca.-->
      <header class="row col s12 m12 l12 card-panel red darken-4 valign-wrapper">

        <div class="logo col s3 m3 l3 valign-wrapper">
          <img class="responsive-img" src="{% static 'images/Logo.png' %}" alt="logo do site Ki Delicia"/>
        </div>

        <div class="links_cadastro col s6 m6 l6">
          <p style="text-align: right;" class="white-text">
          {% if user.is_authenticated %}
          Bem vindo, {{ user.nome }}
          <br/>
          <a href="{% url 'site_receitas:sair' %}" class="white-text">Sair</a>
          {% else %}
          <a href="{% url 'site_receitas:entrar' %}" class="white-text">Entrar</a>
          <br/>
          <a href="{% url 'site_receitas:Cadastrar Usuario' %}" class="white-text">Inscreva-se</a>
          {% endif %}
          </p>
        </div>

        <nav class="nav-wrapper col s3 m3 l3 card-panel red darken-4 valign-wrapper">
          <form>
            <div class="input-field">
              <input id="search" type="search" required>
              <label class="label-icon" for="search"><i class="material-icons">search</i></label>
              <i class="material-icons">close</i>
            </div>
          </form>
        </nav>

      </header>
      <!--nave contendo link de algumas páginas.-->
      <nav class="row col s12 m12 l12 card-panel red darken-4 valign-wrapper">

        <div class="nav-wrapper">
          <ul id="nav-mobile" class="left hide-on-med-and-down">
            <!--Colocar nos href os caminhos para as respectivas páginas após incluir os urls.-->
            <li><a href="{% url 'site_receitas:home' %}">Home</a></li>
            <li><a href="{% url 'site_receitas:home' %}">Receitas</a></li>
            <li><a href="{% url 'site_receitas:Salgados' %}">Salgados</a></li>
            <li><a href="{% url 'site_receitas:Doces' %}">Doces</a></li>
            <li><a href="{% url 'site_receitas:Bebidas' %}">Bebidas</a></li>
            <li><a href="{% url 'site_receitas:Cadastrar Usuario' %}">Increva-se</a></li>
          </ul>
        </div>

      </nav>

      <section class="col s12 m8 l8">
        <!--Aqui para cada página serão inseridos as informações pertinentes aquela página.-->
        {% block content %}{% endblock %}
      </section>

      <aside class="col s12 m4 l4 card-panel red darken-4">
        <!--Conteudo relacionado ao conteudo principal-->
        <ul class="collection">
          <li class="collection-item card-panel red darken-4"><a href="{% url 'site_receitas:TelaCadastrarReceita' %}" class="white-text">Cadastrar Receita</a></li>
          <li class="collection-item card-panel red darken-4"><a href="" class="white-text">Mais Acessadas</a></li>
          <li class="collection-item card-panel red darken-4"><a href="" class="white-text">Top 10 - Semana</a></li>
          <li class="collection-item card-panel red darken-4"><a href="" class="white-text">Usuários</a></li>
          <li class="collection-item card-panel red darken-4"><a href="" class="white-text">Seja um Mestre Confeiteiro</a></li>
        </ul>
      </aside>

      <footer class="col s12 m12 l12 card-panel red darken-4 page-footer">
        <div class="row">
          <div class="col s12 m12 l12">
            <h5 class="white-text">Desenvolvedores</h5>
            <p class="white-text">Augusto Torres dos Santos</p>
            <p class="white-text">Creunivar Toledo de Abreu</p>
            <p class="white-text">Guilherme José Acra</p>
          </div>
        </div>

        <div class="footer-copyright">
            © 2017 Copyright - Todos os direitos reservados.
        </div>

      </footer>

    </div>
  </body>

</html>

BackEnd/site_receitas/templates/bebidas.html
{% extends "base.html" %}

{% block content %}
<article class="row Bebidas">
  <h3>Bebidas</h3>

  <div class="row">

    {% for bebida in bebidas %}
    <div class="col s12 m6 l4">
      <div class="card medium">
        <div class="card-image">
          <a href="{% url 'site_receitas:detalheReceita' bebida.id %}"><img src="/{{ bebida.imagens.0.imagem }}" alt="Imagem da receita: {{ bebida.nome_receita }}"/></a>
          <span class="card-title">{{ bebida.nome_receita }}</span>
        </div>

        <div class="card-content">
          <p>{{ bebida.descricao }}</p>
          <p><b>Por: </b>{{ bebida.autor }}</p>
          <p><b>Nota: </b>{{ bebida.rating }} ({{ bebida.num_votos }} avaliações)</p>
        </div>

        <div class="card-action">
          <a href="{% url 'site_receitas:detalheReceita' bebida.id %}">Receita</a>
        </div>
      </div>
    </div>
    {% endfor %}

  </div>
</article>
{% endblock content %}

BackEnd/site_receitas/templates/detalheReceita.html
{% extends "base.html" %}

{% block content %}
{% load static %}
<script type="text/javascript" src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/js-cookie@2/src/js.cookie.min.js"></script>
<script type="text/javascript" src="{% static 'js/materialize.js' %}"></script>
<script type="text/javascript" src="{% static 'js/enviar_comentario.js' %}"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/rateYo/2.3.2/jquery.rateyo.min.js"></script>

<div class="row">
<div class="col s12 m12 l10">
<article>
   <h1>
      <div itemprop="receitas" itemscope itemtype="http://schema.org/Receitas">
          <span itemprop="name">{{ receita.nome_receita }}</span>
      </div>
  </h1><br>
    <p>
        <div itemprop="autor" itemscope itemtype="http://schema.org/Person">
        Autor(a):<span itemprop="Autor(a):">{{ receita.autor }}</span>, <span itemprop="Date">{{ receita.dataCadastro }}</span>
        </div>
    </p>
    <p>{{ receita.descricao }}</p>
    <div itemscope itemtype="http://Schema.org/Receitas">
      <img  src="/{{ receita.imagens.0.imagem }}" title="Imagem da receita: {{ receita.nome_receita }}" alt="Imagem da receita: {{ receita.nome_receita }}" style="max-width: 100%;"/>
    </div>

  <h2>Ingredientes</h2>
    <ul>
        {% for ingrediente in receita.ingredientes %}
		<li>{{ ingrediente.quantidade}} {{ ingrediente.unidade}} de {{ ingrediente.nome_ingrediente}}</li>
        {% endfor %}
    </ul>

    <h2>Modo de Preparo</h2>
    <p>
        {{receita.instrucoes_preparo}}
    </p>

    <div class="input-field col s12 m12 l6">
      <a class="btn waves-effect waves-light" href="{% url 'site_receitas:simples_xml' 'simples' receita.id %}" style="min-width: 210px">Versão impressão</a>
    </div>

    <div class="input-field col s12 m12 l6">
      <a class="btn waves-effect waves-light" href="{% url 'site_receitas:simples_xml' 'xml' receita.id %}" style="min-width: 210px">Versão XML</a>
    </div>

    <div class="input-field col s12 m12 l6">
      <p><b>Nota: </b>{{ receita.rating }} ({{ receita.num_votos }} avaliações)</p>

    </div>
</article>
<article>
  <div class="col s12 m12 l12">
    <h3>Comentários:</h3>
    {% if user.is_authenticated %}
    <form id="cadastroComentario" action="#" method="post" class="col s12">
      {% csrf_token %}
      <input type="hidden" id="fk_usuario_comentario" name="fk_usuario_comentario" value="{{ user.id }}">
      <input type="hidden" id ="fk_receita_comentario" name="fk_receita_comentario" value="{{ receita.id }}">
      <!--Autor-->
      <div class="row">
        <div class="input-field col s11 m12">
          <label for="autor">Autor: </label>
          <input type="text" name="autor" id="autor" maxlength="100" value="{{user.nome}}" disabled size="30">
        </div>
      </div>

      <!--Comentário-->
      <div class="row">
        <div class="input-field col s11 m12">
          <label for="nome">Comentário: </label>
          <textarea class="materialize-textarea" id="texto_comentario" rows="5" cols="40" maxlength="300" required></textarea>
        </div>
      </div>
      <div id="rateYo"></div>
      <br/>
      <button class="btn waves-effect waves-light" type="submit" name="action">Comentar
        <i class="material-icons right">comment</i>
      </button>
    </form>
    {% else %}
    <p class="red-text">É necessário entrar para comentar!!</p>
    {% endif %}
    {% for comentario in receita.comentarios reversed %}
    <div class="input-field col s11 m12">
      <div class="card" style="background-color: rgba(255,255,255,0.5);">
        <div class="card-content">
          <span class="card-title">{{ comentario.nome_usuario }}:</span>
          <p>{{ comentario.texto_comentario }}</p>
        </div>
      </div>
    </div>
    {% endfor %}
  </div>
</article>
</div>
</div>

{% endblock content %}

BackEnd/site_receitas/templates/doces.html
{% extends "base.html" %}

{% block content %}
<article class="row Doces">
  <h3>Doces</h3>

  <div class="row">

    {% for doce in doces %}
    <div class="col s12 m6 l4">
      <div class="card medium">
        <div class="card-image">
          <a href="{% url 'site_receitas:detalheReceita' doce.id %}"><img src="/{{ doce.imagens.0.imagem }}" alt="Imagem da receita: {{ doce.nome_receita }}"/></a>
          <span class="card-title">{{ doce.nome_receita }}</span>
        </div>

        <div class="card-content">
          <p>{{ doce.descricao }}</p>
          <p><b>Por: </b>{{ doce.autor }}</p>
          <p><b>Nota: </b>{{ doce.rating }} ({{ doce.num_votos }} avaliações)</p>
        </div>

        <div class="card-action">
          <a href="{% url 'site_receitas:detalheReceita' doce.id %}">Receita</a>
        </div>
      </div>
    </div>
    {% endfor %}

  </div>
</article>
{% endblock content %}

BackEnd/site_receitas/templates/entrar.html
{% extends "base.html" %}

{% block content %}
<section class="col s12 m8 l8">
        <div class="row">
            <h2>Entrar</h2>
            <p class="red-text">{{ errors }}</p>
            <form action="{% url 'site_receitas:entrar' %}" method="post" class="col s12">
                {% csrf_token %}
                <div class="row">
                    <!--Nome de usuário-->
                    <div class="input-field col s12 m8">
                        <input class="validate" type="email" id="usuario" name="nome_usuario" size="30" maxlength="50" required title="Precisa ser um e-mail" autofocus>
                        <label class="active" for="usuario" data-error="Usuário é um e-mail">
                            Nome de usuário (e-mail):
                        </label>
                    </div>
                    <!--Senha-->
                    <div class="input-field col s12 m8">
                        <input class="validate" type="password" name="senha" id="senha" size="15" maxlength="15" required pattern=".{8,}" title="8 ou mais caracteres">
                        <label class="active" for="senha" data-error="Mínimo de 8 caracteres">
                            Senha:
                        </label>

                    </div>
                </div>

                <button class="btn waves-effect waves-light" type="submit" name="action">Entrar
                <i class="material-icons right">forward</i>
            </button>
            </form>
        </div>
</section>
{% endblock content %}

BackEnd/site_receitas/templates/index.html
{% extends "base.html" %}

{% block content %}
<article class="row Doces">
  <h3>Doces</h3>

  <div class="row">

    {% for doce in doces %}
    <div class="col s12 m6 l4">
      <div class="card medium">
        <div class="card-image">
          <a href="{% url 'site_receitas:detalheReceita' doce.id %}"><img src="/{{ doce.imagens.0.imagem }}" alt="Imagem da receita: {{ doce.nome_receita }}"/></a>
          <span class="card-title">{{ doce.nome_receita }}</span>
        </div>

        <div class="card-content">
          <p>{{ doce.descricao }}</p>
          <p><b>Nota: </b>{{ doce.rating }}</p>
        </div>

        <div class="card-action">
          <a href="{% url 'site_receitas:detalheReceita' doce.id %}">Receita</a>
        </div>
      </div>
    </div>
    {% endfor %}

  </div>
  <p class="right-align"><a href="{% url 'site_receitas:Doces' %}">+ Receitas >></a></p>
</article>

<article class="row Salgados">
  <h3>Salgados</h3>

  <div class="row">

    {% for salgado in salgados %}
    <div class="col s12 m6 l4">
      <div class="card medium">
        <div class="card-image">
          <a href="{% url 'site_receitas:detalheReceita' salgado.id %}"><img src="/{{ salgado.imagens.0.imagem }}" alt="Imagem da receita: {{ salgado.nome_receita }}"/></a>
          <span class="card-title" style="text-transform: capitalize;">{{ salgado.nome_receita }}</span>
        </div>

        <div class="card-content">
          <p>{{ salgado.descricao }}</p>
          <p><b>Nota: </b>{{ salgado.rating }}</p>
        </div>

        <div class="card-action">
          <a href="{% url 'site_receitas:detalheReceita' salgado.id %}">Receita</a>
        </div>
      </div>
    </div>
    {% endfor %}

  </div>
  <p class="right-align"><a href=" {% url 'site_receitas:Salgados' %}">+ Receitas >></a></p>
</article>

<article class="row Bebidas">
  <h3>Bebidas</h3>

  <div class="row">

    {% for bebida in bebidas %}
    <div class="col s12 m6 l4">
      <div class="card medium">
        <div class="card-image">
          <a href="{% url 'site_receitas:detalheReceita' bebida.id %}"><img src="/{{ bebida.imagens.0.imagem }}" alt="Imagem da receita: {{ bebida.nome_receita }}"/></a>
          <span class="card-title">{{ bebida.nome_receita }}</span>
        </div>

        <div class="card-content">
          <p>{{ bebida.descricao }}</p>
          <p><b>Nota: </b>{{ bebida.rating }}</p>
        </div>

        <div class="card-action">
          <a href="{% url 'site_receitas:detalheReceita' bebida.id %}">Receita</a>
        </div>
      </div>
    </div>
    {% endfor %}

  </div>
  <p class="right-align"><a href="{% url 'site_receitas:Bebidas' %}">+ Receitas >></a></p>
</article>
{% endblock content %}